---
ID: "dccc6d3c-a640-4afe-b56d-8f15e47400b0"
Parent: "d139adc1-daa8-40b8-814e-1722f6ed88e5"
Template: "d139adc1-daa8-40b8-814e-1722f6ed88e5"
Path: /sitecore/templates/Foundation/Ordercloud/Folder/Ordercloud Global Root Settings/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{CE046CA7-2C10-45E7-9214-3A8829A15AC6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210922T084321Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0a268623-710c-43a8-ac74-eb90af459a1c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210922T084457Z
