---
ID: "29b37208-9e25-4c32-afe3-8ff7388a19a1"
Parent: "5be0dda4-79ff-4d1d-ad81-33c489ccdbd1"
Template: "5be0dda4-79ff-4d1d-ad81-33c489ccdbd1"
Path: /sitecore/templates/Foundation/Environment/Folders/Global Data/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {86C800B9-9668-4861-A2A7-C9DE35E13CDF}
    {D139ADC1-DAA8-40B8-814E-1722F6ED88E5}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210830T104141Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bddb039b-b71b-41b0-a36c-d21a46c7af2e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210922T084514Z
