---
ID: "74b23dcb-eb97-4712-97ff-2f4f583c75c1"
Parent: "b200729a-65f4-4e0a-b6a9-478c6e6c732c"
Template: "ce046ca7-2c10-45e7-9214-3a8829a15ac6"
Path: /sitecore/content/Global/Ordercloud/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "088ea09b-28de-4023-acfa-bf67dceac0e7"
      Hint: Catalog Content Root
      Value: "{C5792BF3-94E4-4FF3-8271-019EAC264319}"
    - ID: "18e5b8b8-1093-45fe-a3d1-49fced88e97e"
      Hint: AuthUrl
      Value: "https://sandboxapi.ordercloud.io"
    - ID: "1baa5d80-3358-4cf8-bce3-3076ce74d884"
      Hint: Catalog
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210924T135302Z
    - ID: "29e37891-4002-4dbc-8e52-22554aaf2b06"
      Hint: ClientSecret
      Value: 
    - ID: "2ba9e7d8-449a-43dd-9064-2a5566f9c16f"
      Hint: Client Side Roles
      Value: 
    - ID: "40f72b5d-d48b-4124-80b4-371ac4279fa4"
      Hint: Client Side Password
      Value: 
    - ID: "5073dc66-4ce3-4451-aac9-7938397728a6"
      Hint: Client Side Username
      Value: 
    - ID: "5888304c-162e-4e29-a8f8-018038407a88"
      Hint: Username
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac57a9b1-c6ee-45c6-a443-380773ad8ab6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d2a39a27-90f2-4aaf-a7e2-8c1ffbc32c08"
      Hint: ClientId
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220222T063839Z
    - ID: "ef1fb986-d333-4b7a-a578-8f6a2796ad0c"
      Hint: Password
      Value: 
