---
ID: "85be5c83-70e6-5b7d-bb5e-1c188a48e594"
Parent: "e802f507-279c-5e99-82e4-f6289bcf7b53"
Template: "e802f507-279c-5e99-82e4-f6289bcf7b53"
Path: "/sitecore/templates/Project/jssdemo/GraphQL-IntegratedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210827T110945Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dab27fd0-5ce3-438f-b0b4-0a913b3554cd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T110945Z
