---
ID: "eba37c21-a517-40b1-b42a-b5a89e7cec05"
Parent: "e883eb75-8af6-4eda-8beb-ecd29ba7d08e"
Template: "e883eb75-8af6-4eda-8beb-ecd29ba7d08e"
Path: /sitecore/templates/Foundation/Products/Product Variant/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{A9776D70-37C3-43E3-B150-D88ED28A08FA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211103T125131Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a850a33a-7a8b-4bdc-bc35-746160b96378"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211103T161101Z
