---
ID: "d671ee63-245c-430a-b9c9-2576609247a6"
Parent: "cda16873-6b24-4755-aa6e-23bf419f34eb"
Template: "ec6d62a5-5d00-4329-8958-8ac1ad100ebb"
Path: /sitecore/content/Applications/Content Editor/Ribbons/Strips/Products
SharedFields:
- ID: "12c1ceb4-f549-472a-97ed-99bff70eb84e"
  Hint: ID
  Value: ProductsStrip
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20061120T132331
    - ID: "453004db-0396-4d30-80d6-39cfdf244f32"
      Hint: Hidden by Default
      Value: 1
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: Products
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0991d5a-ca35-4e8e-a850-f2d86d7c728b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20060216T093917
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T092620Z
