---
ID: "58b7ea33-aca3-40e7-bfb1-fc93b2eed4cd"
Parent: "0826d4fa-c48d-406a-9ea9-ea168f99612f"
Template: "0826d4fa-c48d-406a-9ea9-ea168f99612f"
Path: /sitecore/templates/Foundation/Products/Category/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6F2E2015-355C-4439-9BE5-FC7518A0F1BB}
    {0826D4FA-C48D-406A-9EA9-EA168F99612F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210830T102944Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59f0c8c5-0918-4baa-b68e-49985d47a97d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211103T180818Z
