---
ID: "04fa2d0c-e6e0-59e1-8f42-92551503f19c"
Parent: "c0fc5bf8-ad55-58c3-a779-2ca65b9eff88"
Template: "c0fc5bf8-ad55-58c3-a779-2ca65b9eff88"
Path: "/sitecore/templates/Project/jssdemo/Styleguide-Section/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210827T110947Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd603a39-67ca-4ac8-8899-0b19e791c681"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T110947Z
