---
ID: "aac87abd-80eb-58a2-9e5e-92d7ab6e9e9a"
Parent: "867a22c1-78f1-5881-8e2e-5f6c10dce762"
Template: "867a22c1-78f1-5881-8e2e-5f6c10dce762"
Path: "/sitecore/templates/Project/jssdemo/Styleguide-ItemLink-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210827T110939Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d50709e6-80ce-4d82-9b1f-8f7d292a499b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T110939Z
