---
ID: "2886f04a-8dbc-597a-b323-a5abe752b2fe"
Parent: "9f98de13-bf1d-551d-8dc3-3d9c00026a5e"
Template: "9f98de13-bf1d-551d-8dc3-3d9c00026a5e"
Path: "/sitecore/templates/Project/jssdemo/Styleguide-FieldUsage-ContentList/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210827T110941Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "802575c8-678b-4cd7-a2eb-e3e3b1ee23ca"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T110941Z
