---
ID: "4d8f3663-32de-5d37-9307-0d27f2d7b96d"
Parent: "a29c7298-956f-53a8-b9fb-cd6b2e4b9e4b"
Template: "a29c7298-956f-53a8-b9fb-cd6b2e4b9e4b"
Path: "/sitecore/templates/Project/jssdemo/GraphQL-ConnectedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210827T110945Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "edc3b806-0df7-4189-b666-de8a87f5a36d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210827T110945Z
